[package]
name = "star_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
curl = "0.4.47"
fitrs = "0.5.0"
gl = "0.14.0"
glam = "0.30.3"
glfw = "0.59.0"

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
codegen-units = 1
